# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-04 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190804_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='permissions',
            new_name='peimissions',
        ),
    ]
